enrg_df<-read.csv("exdata_data_household_power_consumption/household_power_consumption.txt", sep=";", colClasses="character")
enrg_df$Date<-as.Date(enrg_df$Date, format="%d/%m/%Y")
begin_dt<- as.Date("2007-02-1")
end_dt<- as.Date("2007-02-2")
test4<-enrg_df[enrg_df$Date==begin_dt | enrg_df$Date==end_dt,]
png(file="plot4.png")
par(mfcol = c(2,2))
plot(test4[,3], type="l", ylab="Global Active Power", xaxt="n", xlab="")
axis(side=1, labels=c("Thu", "Fri", "Sat"), at=c(0, 1440, 2880))

x<-as.numeric(test4[,7])
y<-as.numeric(test4[,8])
z<-as.numeric(test4[,9])
v<-as.numeric(test4[,5])
g<-as.numeric(test4[,4])

plot(x, type="l", xaxt="n", xlab="", ylab="Energy sub metering")
lines(y, type="l", col="red")
lines(z, type="l", col="blue")
axis(side=1, labels=c("Thu", "Fri", "Sat"), at=c(0, 1440, 2880))
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(v, type="l", xaxt="n", xlab="datetime", ylab="Voltage")
axis(side=1, labels=c("Thu", "Fri", "Sat"), at=c(0, 1440, 2880))
plot(g, type="l", xaxt="n", xlab="datetime", ylab="Global_reactive_power")
axis(side=1, labels=c("Thu", "Fri", "Sat"), at=c(0, 1440, 2880))
dev.off()